spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/electronic_db
    username: root
    password: nhatphu234aA.
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    hibernate:
      ddl-auto: none
  messages:
    basename: messageErrors
    fallback-to-system-locale: false
  web:
    locale: vi_VN
    locale-resolver: fixed
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: ebonikshop@gmail.com
    password: aibzzxjrffupjjrf
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
  liquibase:
    change-log: classpath:db/changelog.xml
    enabled: false #false is not use liquibase when no have new design
  logging:
    level:
      org:
        hibernate: ERROR
  app:
    cors:
      allowedOrigins: http://localhost:3000,http://localhost:3001 #domain of user frontend
 #domain of admin frontend


